baseURL = "http://wwww.yasinacerik.com/"
languageCode = "en-us"
title = "Yasin"
theme="archie"
copyright = "© Yasin"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=4
[params]
	favicon="https://img.icons8.com/officel/16/000000/chevron-right.png"
	og_image="https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
	mode="auto"
	featherIconsCDN=true
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	description = "Archie is a Minimal and Clean theme for Hugo"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ysnacrk"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/koka_koala"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4