baseURL = "https://yasinacierik.com/"
languageCode = "en-us"
title = "Yasin"
theme="archie"
copyright = "© Yasin"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=4
googleAnalytics = "UA-172226750-1"
[params]
	favicon=""
	og_image="https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
	mode="light"
	featherIconsCDN=true
	subtitle = "My Personal Blog"
	description = "Archie is a Minimal and Clean theme for Hugo"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ysnacrk"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/koka_koala"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
